
require_relative 'piece'
require_relative 'rook'
require_relative 'knight'
require_relative 'queen'
require_relative 'bishop'
require_relative 'pawn'
require_relative 'king'
require_relative 'NullPiece'
require_relative 'slideable'
require_relative 'stepable'